#ifndef GAMEPARAMETERS_H
#define GAMEPARAMETERS_H

enum WINDOW_PARAMETERS {
	WINDOW_DIMENSION = 1000,
	WINDOW_BOARD_WIDTH = WINDOW_DIMENSION,
	WINDOW_BOARD_HEIGHT = WINDOW_DIMENSION - 100,
	WINDOW_FOOTER_WIDTH = WINDOW_DIMENSION,
	WINDOW_FOOTER_HEIGHT = WINDOW_DIMENSION - WINDOW_BOARD_HEIGHT,
	WINDOW_FOOTER_X_POSITION = 0,
	WINDOW_FOOTER_Y_POSITION = WINDOW_BOARD_HEIGHT,
	FIELD_DIMENSION = 50
};

enum BOARD_PARAMETERS {
	BOARD_ROWS_COUNT = WINDOW_BOARD_HEIGHT / FIELD_DIMENSION,
	BOARD_COLUMNS_COUNT = WINDOW_BOARD_WIDTH / FIELD_DIMENSION
};

enum CHINCHILLA_PARAMETERS {
	CHINCHILLA_WIDTH = 200,
	CHINCHILLA_HEIGHT = 150,
	CHINCHILLA_ROW_FIELDS_COUNT = CHINCHILLA_WIDTH / FIELD_DIMENSION,
	CHINCHILLA_COL_FIELDS_COUNT = CHINCHILLA_HEIGHT / FIELD_DIMENSION,
	CHINCHILLA_FIELDS_COUNT = CHINCHILLA_ROW_FIELDS_COUNT
			* CHINCHILLA_COL_FIELDS_COUNT,
	SPEED = 500
};

enum ALMOND_PARAMETERS {
	ALMOND_WIDTH = 50,
	ALMOND_HEIGHT = 50,
	ALMOND_ROW_FIELDS_COUNT = 1,
	ALMOND_COL_FIELDS_COUNT = 1,
	ALMONDS_COUNT = 5
};

enum GAME_PARAMETERS {
	TIME_LIMIT = 20
};

#endif
